### PR TITLE
chore(di): throw an error when registry is not found

### PR DESCRIPTION
**Pull request by isqua**
/cc @awinogradov

### CODE REVIEW

**Comment by isqua** [comment]
oh no mq there

**Comment by isqua** [comment]
pls ship it to web4

**Comment by isqua** [comment]
@awinogradov publish plz

**Comment by awinogradov** [comment]
Successfully published:
 - @bem-react/classname@1.4.4
 - @bem-react/core@1.6.4
 - @bem-react/di@1.5.3

**Pull request merged**
